name: CI/CD Fake Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout c贸digo
        uses: actions/checkout@v4

      - name: Simular Build
        run: |
          echo "Iniciando etapa de BUILD..."
          echo "Compilando aplicaci贸n..."
          echo "Build completado con 茅xito."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout c贸digo
        uses: actions/checkout@v4

      - name: Simular Tests
        run: |
          echo "Iniciando etapa de TEST..."
          echo "Ejecutando pruebas unitarias..."
          echo "Todos los tests pasaron 锔."

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout c贸digo
        uses: actions/checkout@v4

      - name: Simular Deploy
        run: |
          echo "Iniciando etapa de DEPLOY..."
          echo "Empaquetando artefactos..."
          echo "Enviando aplicaci贸n al servidor..."
          echo "Deploy realizado con 茅xito ."